#!/bin/bash

echo "🔧 CORRECTED ATP SECURITY DEPLOYMENT"
echo "====================================="
echo ""
echo "The previous command failed due to quote parsing and PATH issues."
echo "Use this CORRECTED command:"
echo ""
echo "──────────────────────────────────────────────────────────────────"
echo "ssh root@165.227.13.206 'cd /opt/atp && git pull origin main && npm install && npm run build && /usr/local/bin/pm2 restart atp-website && /usr/local/bin/pm2 list && /usr/bin/curl -I https://agenttrustprotocol.com/policies'"
echo "──────────────────────────────────────────────────────────────────"
echo ""
echo "Key fixes:"
echo "  • Single quotes (not double) to prevent parsing issues"
echo "  • Full paths for pm2 and curl commands"
echo "  • Corrected to /opt/atp directory"
echo ""
echo "Expected result: HTTP/1.1 403 Forbidden"
echo ""
echo "Alternative (if pm2/curl paths differ):"
echo "ssh root@165.227.13.206 'source ~/.bashrc && cd /opt/atp && git pull origin main && npm install && npm run build && pm2 restart atp-website && pm2 list && curl -I https://agenttrustprotocol.com/policies'"