#!/bin/bash
echo "🔍 DIAGNOSING DEPLOYMENT ISSUE"
echo "=============================="
echo ""
echo "Run this command to diagnose:"
echo ""
echo "ssh root@165.227.13.206 '"
echo "echo '🏠 Current working directory:'"
echo "pwd"
echo "echo ''"
echo "echo '📂 Contents of /opt/atp:'"
echo "ls -la /opt/atp 2>/dev/null || echo 'Directory not found'"
echo "echo ''"
echo "echo '🔧 PM2 process details:'"
echo "pm2 describe atp-website"
echo "echo ''"
echo "echo '📄 Looking for middleware.ts:'"
echo "find /opt -name 'middleware.ts' 2>/dev/null | head -5"
echo "echo ''"
echo "echo '🔍 Checking git status:'"
echo "cd /opt/atp && git log --oneline -3 2>/dev/null || echo 'Not a git repo'"
echo "echo ''"
echo "echo '📦 Node.js processes:'"
echo "ps aux | grep node | grep -v grep"
echo "'"
